// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sacvseswikvuyubyfldw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhY3ZzZXN3aWt2dXl1YnlmbGR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDgwNjUsImV4cCI6MjA3MTc4NDA2NX0.BiF73vxxm1JbZzDwZ9p84UbbS11Z-goQHgWiJfxnNl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});